#!/bin/bash
#+-----------------------------------------------------------+
#|                                                           |
#| Lib for URL manipulation                                  |
#|                                                           |
#+-----------------------------------------------------------+
#| version : VERSION_SCRIPT                                  |
#+-----------------------------------------------------------+

URL0=`echo $HOSTNAME | sed 's|,.*||g' | sed "s|'||g"`
URL0_HTTP=`echo $URL0 | sed 's|http[s]*://||g' |sed 's|/.*||g'`
URL_ALIAS=`echo $HOSTNAME | sed 's|,| |g' | sed 's|http[s]*://||g'`
URL=`echo $URL_ALIAS | sed 's|/|\.|g'`